name: 'My Custom Action'
description: 'Say Hello'
author: 'LTomer'

inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: 'World'
  regex:
    description: 'Filter Environment Variables that should be set as secrets (regex)'
    required: false
    default: '.*(cert|password|token).*'
  ignoreCase:
    description: 'Enable case-insensitive regex matching'
    required: false
    default: 'true'
    
runs:
  using: 'node24'
  main: 'dist/index.js'