name: Say Hello

on:
  workflow_dispatch:

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variable
        run: echo "my_var=test-TEST" >> $GITHUB_ENV
      - name: Show Environment Variables
        uses: LTomer/env-inspector-action@v1
      - name: Template Action
        uses: ./
        with:
          name: 'LTomer'
      - name: Show Environment Variables
        uses: LTomer/env-inspector-action@v1
